# Generated by Django 3.1.6 on 2021-02-04 10:51

import as207960_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_twilioaccount', primary_key=True, serialize=False)),
                ('account_sid', models.CharField(max_length=255)),
                ('account_token', models.CharField(max_length=255)),
            ],
        ),
    ]
