# Generated by Django 3.1.6 on 2021-02-04 12:51

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20210204_1251'),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_smsagent', primary_key=True, serialize=False)),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_agent', to='messaging.brand')),
                ('twilio_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_agents', to='sms.twilioaccount')),
            ],
        ),
    ]
