# Generated by Django 3.1.6 on 2021-02-04 17:23

import as207960_utils.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSISDN',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_vsmskey', primary_key=True, serialize=False)),
                ('msisdn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('vsms_public_key', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MSISDN',
                'verbose_name_plural': 'MSISDNs',
            },
        ),
    ]
