kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: messaging-django-static
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: messaging-django-media
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: messaging-django-conf
data:
  HOST: "messaging.as207960.net,messaging-nginx"
  DJANGO_SETTINGS_MODULE: as207960_messaging.settings
  EXTERNAL_URL: "https://messaging.as207960.net"
  SENTRY_ENVIRONMENT: "prod"
  DB_HOST: "cockroachdb"
  DB_NAME: "messaging"
  KEYCLOAK_SERVER_URL: "https://sso.as207960.net/"
  KEYCLOAK_REALM: master
  KEYCLOAK_SCOPES: "openid email profile"
  KEYCLOAK_CLIENT_ID: "messaging"
  BM_SA_LOCATION: "/google-bm-creds/bm-sa.json"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-django
  labels:
    app: messaging
    part: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
      part: django
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: messaging
        part: django
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: messaging-django-static
        - name: media
          persistentVolumeClaim:
            claimName: messaging-django-media
        - name: google-bm-creds
          secret:
            secretName: messaging-google-bm-creds
      initContainers:
        - name: django
          image: as207960/messaging-django:(version)
          imagePullPolicy: Always
          command: ["sh", "-c", "python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py sync-keycloak"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/google-bm-creds/"
              name: google-bm-creds
          envFrom:
            - configMapRef:
                name: messaging-django-conf
            - secretRef:
                name: messaging-db-creds
              prefix: "DB_"
            - secretRef:
                name: messaging-django-secret
            - secretRef:
                name: messaging-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: messaging-celery
              prefix: "CELERY_"
      containers:
        - name: gunicorn
          image: as207960/messaging-django:(version)
          imagePullPolicy: Always
          command: ["gunicorn", "-w", "8", "-b", "[::]:8000", "--forwarded-allow-ips", "*", "--access-logfile", "-", "--timeout=90", "as207960_messaging.wsgi:application"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/google-bm-creds/"
              name: google-bm-creds
          envFrom:
            - configMapRef:
                name: messaging-django-conf
            - secretRef:
                name: messaging-db-creds
              prefix: "DB_"
            - secretRef:
                name: messaging-django-secret
            - secretRef:
                name: messaging-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: messaging-celery
              prefix: "CELERY_"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-celery
  labels:
    app: messaging
    part: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging
      part: celery
  template:
    metadata:
      annotations:
        cni.projectcalico.org/ipv6pools: "[\"default-ipv6-ippool\"]"
      labels:
        app: messaging
        part: celery
    spec:
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: messaging-django-static
        - name: media
          persistentVolumeClaim:
            claimName: messaging-django-media
        - name: google-bm-creds
          secret:
            secretName: messaging-google-bm-creds
      containers:
        - name: grpc
          image: as207960/messaging-django:(version)
          imagePullPolicy: Always
          command: ["celery",  "-A", "as207960_messaging", "worker", "--loglevel=INFO", "-c", "32"]
          ports:
            - containerPort: 50051
          volumeMounts:
            - mountPath: "/app/static/"
              name: static
            - mountPath: "/app/media/"
              name: media
            - mountPath: "/google-bm-creds/"
              name: google-bm-creds
          envFrom:
            - configMapRef:
                name: messaging-django-conf
            - secretRef:
                name: messaging-db-creds
              prefix: "DB_"
            - secretRef:
                name: messaging-django-secret
            - secretRef:
                name: messaging-keycloak
              prefix: "KEYCLOAK_"
            - secretRef:
                name: messaging-celery
              prefix: "CELERY_"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-django
  labels:
    app: messaging
    part: django
spec:
  selector:
    app: messaging
    part: django
  ports:
    - port: 8000
      targetPort: 8000
      name: gunicorn
