# Generated by Django 3.1.2 on 2020-11-14 13:11

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_gbcbrand', primary_key=True, serialize=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.brand')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessMessagingAgent',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_gbmagent', primary_key=True, serialize=False)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gbc.brand')),
            ],
        ),
    ]
