# Generated by Django 3.1.3 on 2020-12-09 17:22

import as207960_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_gbcauthstate', primary_key=True, serialize=False)),
                ('google_state', models.TextField()),
                ('redirect_uri', models.URLField()),
                ('auth_code', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
