# Generated by Django 3.1.6 on 2021-02-03 17:30

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0007_auto_20201128_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_rcsagent', primary_key=True, serialize=False)),
                ('service_account_key', models.TextField()),
                ('subscription_name', models.CharField(max_length=255)),
                ('pull_subscription', models.BooleanField(blank=True, default=False)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='messaging.brand')),
            ],
        ),
    ]
