# Generated by Django 3.1.6 on 2021-02-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='region',
            field=models.CharField(default='europe', max_length=64),
        ),
    ]
