# Generated by Django 3.1.6 on 2021-02-03 22:25

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20210203_2003'),
        ('rcs', '0002_agent_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSIDN',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_rcsmsidn', primary_key=True, serialize=False)),
                ('msidn', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('supports_rcs', models.BooleanField(blank=True, default=False)),
                ('supports_revocation', models.BooleanField(blank=True, default=False)),
                ('supports_rich_card_standalone', models.BooleanField(blank=True, default=False)),
                ('supports_rich_card_carousel', models.BooleanField(blank=True, default=False)),
                ('supports_action_calendar', models.BooleanField(blank=True, default=False)),
                ('supports_action_dial', models.BooleanField(blank=True, default=False)),
                ('supports_action_url', models.BooleanField(blank=True, default=False)),
                ('supports_action_share_location', models.BooleanField(blank=True, default=False)),
                ('supports_action_view_location', models.BooleanField(blank=True, default=False)),
                ('supports_payments_v1', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='agent',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rcs_agent', to='messaging.brand'),
        ),
    ]
