# Generated by Django 3.1.6 on 2021-02-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0003_auto_20210203_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='msidn',
            name='agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rcs.agent'),
            preserve_default=False,
        ),
    ]
