# Generated by Django 3.1.6 on 2021-02-03 23:22

import as207960_utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcs', '0005_auto_20210203_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='msidn',
            old_name='msidn',
            new_name='msisdn',
        ),
        migrations.AlterField(
            model_name='msidn',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='messaging_rcsmsisdn', primary_key=True, serialize=False),
        ),
    ]
