# Generated by Django 3.1.2 on 2020-11-14 13:11

import as207960_utils.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_brand', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('webhook_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', as207960_utils.models.TypedUUIDField(data_type='messaging_message', primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('I', 'Incoming'), ('O', 'Outgoing')], max_length=1)),
                ('state', models.CharField(choices=[('A', 'Accepted'), ('E', 'Dispatched'), ('D', 'Delivered'), ('R', 'Read'), ('F', 'Failed')], default='A', max_length=1)),
                ('platform', models.CharField(choices=[('google-business-messaging', 'Google Business Messaging')], max_length=255)),
                ('platform_conversation_id', models.CharField(db_index=True, max_length=255)),
                ('platform_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('platform_dedup_id', models.CharField(db_index=True, max_length=255)),
                ('client_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('media_type', models.CharField(max_length=255)),
                ('content', models.JSONField(blank=True, null=True)),
                ('error_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_description', models.TextField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.brand')),
            ],
        ),
    ]
