# Generated by Django 3.1.3 on 2020-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='brand',
            name='resource_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
