# Generated by Django 3.1.3 on 2020-11-20 15:34

import as207960_utils.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_auto_20201114_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='webhook_signing_secret',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='messaging_brand', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='messaging_message', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='representative',
            name='id',
            field=as207960_utils.models.TypedUUIDField(data_type='messaging_representative', editable=False, primary_key=True, serialize=False),
        ),
    ]
