# Generated by Django 3.1.3 on 2020-11-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_auto_20201120_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='authorization_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
