# Generated by Django 3.1.6 on 2021-02-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_auto_20201128_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('google-business-messaging', 'Google Business Messaging'), ('rcs-business-messaging', 'RCS Business Messaging')], max_length=255),
        ),
    ]
