# Generated by Django 3.1.6 on 2021-02-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_auto_20210203_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='platform',
            field=models.CharField(choices=[('google-business-messaging', 'Google Business Messaging'), ('msisdn-messaging', 'MSISDN Messaging')], max_length=255),
        ),
    ]
