# Generated by Django 3.1.6 on 2021-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_auto_20210204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='firebase_short_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
